server:
  port: 8084

spring:
  aplication:
    name: servicio-usuarios

  datasource:
    url: jdbc:h2:mem:usuariosdb
    username: sa
    password: 
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console  # Direccion para acceder a la consola de la bd
                         # Para acceder:  localhost:8084/h2-console
                         # Luego se accede en JDBC con la url del datasource, en este caso jdbc:h2:mem:usuariosdb
                         # Importante poner en postman el puerto de la bd de cada microservicio, en este caso
                         # usuarios tiene el puerto 8084.

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true