server:
  port: 8081

spring:
  aplication:
    name: servicio-productos

  datasource:
    url: jdbc:h2:mem:productosdb
    username: anto
    password: 
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console  # Direccion para acceder a la consola de la bd
                         # Para acceder:  localhost:8081/h2-console
                         # Luego se accede en JDBC con la url del datasource, en este caso jdbc:h2:mem:productosdb
                         # Importante poner en postman el puerto de la bd de cada microservicio, en este caso
                         # productos tiene el puerto 8081, por lo que pasa POSTEAR un producto hay que usar:
                         # http://localhost:8081/api/v3/productos/crearProducto

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true